add check for secrets

diff --git a/.github/workflows/tests_workflow.yml b/.github/workflows/tests_workflow.yml
--- a/.github/workflows/tests_workflow.yml
+++ b/.github/workflows/tests_workflow.yml
@@ -26,23 +26,37 @@ jobs:
 
   test:
     name: Run autotests
+    environment: test
     runs-on: ubuntu-latest
     needs: build
-    environment: test
 
     steps:
       - name: Check out the repo
         uses: actions/checkout@v2
+      - name: Check required secrets
+        run: |
+          missing=""
+          for var in DATABASE_NAME DATABASE_USER DATABASE_PASSWORD DATABASE_HOST DATABASE_PORT; do
+            if [ -z "${{ secrets[$var] }}" ]; then
+              echo "Error: Secret $var is not set."
+              missing=1
+            fi
+          done
+          if [ ! -z "$missing" ]; then
+            exit 1
+          fi
       - name: Set up Docker compose
         uses: docker/setup-compose-action@v1
       - name: Run app in compose and populate db
         working-directory: ./infra
         run: |
-          echo DB_NAME=${{ secrets.DATABASE_NAME }} > .env
-          echo POSTGRES_USER=${{ secrets.DATABASE_USER }} >> .env
-          echo POSTGRES_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
-          echo DB_HOST=${{ secrets.DATABASE_HOST }} >> .env
-          echo DB_PORT=${{ secrets.DATABASE_PORT }} >> .env
+          cat <<EOF > .env
+          DB_NAME=${{ secrets.DATABASE_NAME }}
+          POSTGRES_USER=${{ secrets.DATABASE_USER }}
+          POSTGRES_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
+          DB_HOST=${{ secrets.DATABASE_HOST }}
+          DB_PORT=${{ secrets.DATABASE_PORT }}
+          EOF
           export IMAGE_TAG=${{ github.sha }}
           docker compose up -d
           docker compose exec app bundle exec rake db:create
